version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.3.2   # ✅ 固定稳定版本，避免 latest 不完整
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=101.35.226.226
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=andy_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=A5%Bd$#a7.Q
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      # ✅ 开启认证
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=zii9LV1IpDwWB0K5DIcT0ETRVOHffooWM/Z2d8J70us=
    ports:
      - "8848:8848"   # ✅ 2.x 版本 UI 端口仍然是 8848
      - "9848:9848"
      - "9849:9849"
    restart: always
