version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=101.35.226.226
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=andy_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=A5%Bd$#a7.Q
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - NACOS_AUTH_TOKEN=zii9LV1IpDwWB0K5DIcT0ETRVOHffooWM/Z2d8J70us= # Add JWT secret
    ports:
      - "8848:8848" # Web UI and client gRPC
      - "9848:9848" # Server gRPC
      - "9849:9849" # Raft communication
    restart: unless-stopped # Changed from always for better control
#    depends_on:
#      - mysql # Ensure MySQL is available if defined
    networks:
      - nacos-network
networks:
  nacos-network:
    driver: bridge