-- ============简历管理表============

CREATE TABLE `resume` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(50) COMMENT '候选人姓名',
    `phone` VARCHAR(20) COMMENT '手机号',
    `email` VARCHAR(100) COMMENT '邮箱',
    `gender` VARCHAR(1) COMMENT '性别（M-男，F-女）',
    `age` INT COMMENT '年龄',
    `education` VARCHAR(20) COMMENT '学历（本科、硕士、博士）',
    `university` VARCHAR(100) COMMENT '毕业院校',
    `major` VARCHAR(100) COMMENT '专业',
    `work_years` INT COMMENT '工作年限',
    `current_position` VARCHAR(100) COMMENT '当前职位',
    `current_company` VARCHAR(200) COMMENT '当前公司',
    `expected_position` VARCHAR(100) COMMENT '期望职位',
    `expected_salary` INT COMMENT '期望薪资（单位：K/月）',
    `expected_city` VARCHAR(50) COMMENT '期望城市',
    `skills` TEXT COMMENT '技能标签（JSON数组）',
    `work_experience` TEXT COMMENT '工作经历（JSON数组）',
    `project_experience` TEXT COMMENT '项目经历（JSON数组）',
    `education_history` TEXT COMMENT '教育经历（JSON数组）',
    `self_evaluation` TEXT COMMENT '自我评价',
    `raw_content` TEXT COMMENT '简历原文（纯文本）',
    `file_path` VARCHAR(500) COMMENT '简历文件路径',
    `file_type` VARCHAR(10) COMMENT '文件类型（pdf、docx）',
    `source` VARCHAR(20) DEFAULT 'upload' COMMENT '简历来源（upload-上传，crawler-爬虫，referral-内推）',
    `parse_status` VARCHAR(20) DEFAULT 'pending' COMMENT '解析状态（pending-待解析，parsing-解析中，success-成功，failed-失败）',
    `parse_error` TEXT COMMENT '解析失败原因',
    `vectorize_status` VARCHAR(20) DEFAULT 'pending' COMMENT '向量化状态（pending-待向量化，success-成功，failed-失败）',
    `indexed` TINYINT DEFAULT 0 COMMENT '是否已索引到ES（0-否，1-是）',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_phone` (`phone`),
    INDEX `idx_parse_status` (`parse_status`),
    INDEX `idx_vectorize_status` (`vectorize_status`),
    INDEX `idx_indexed` (`indexed`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='简历表';
